config/routes.rb
NewApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:new,:create,:destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'

end

app/views/shared/_delete.html.erb
<%= link_to "delete", micropost_path(micropost), method: :delete, data: {confirm: "Are You Sure"}%>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
			<% object.errors.full_messages.each do |i| %>
				<li>* <%= i %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items%>
	</ol>
	<%= will_paginate @feed_items%>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content"> <%= wrap(feed_item.content) %></span>
	<span class="timestamp">
	<% if current_user?(feed_item.user) %>
		<%= wrap("Posted " + time_ago_in_words(feed_item.created_at)+ " ago. " ) %> <%= render 'shared/delete', 		micropost: feed_item %>
	<% else %>
		<%= wrap("Posted " + time_ago_in_words(feed_item.created_at)+ " ago. " ) %>
	<% end%>
	</span>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
		<%= f.label :content, "Content", class: "character-remaining"%>
		<script>
		$(document).ready(function(){

			$('textarea').attr("maxlength", 140)
			remaining_characters();
		  $("#micropost_content").keyup(function(){
				remaining_characters();
			}); 
		});
		
		function remaining_characters(){
			var remaining_char = 140 - $("#micropost_content").val().length;
			$('.character-remaining').text(remaining_char + " characters remaining")
		};
		</script>
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_not_signed_in.html.erb
	<div class="center hero-unit">
		<h1>Welcome to Auster's App</h1>
		<h2>Home Page</h2>
		<%= link_to "Sign Up", signup_path, class: "btn btn-large btn-primary" %>
	</div>
	

app/views/shared/_signed_in.html.erb
	<div class="row">
		<aside class="span4">
			<section>
				<%= render 'shared/user_info'%>
			</section>
			<section>
				<%= render 'shared/stats' %>
			</section>
			<section>
				<%= render 'shared/micropost_form'%>
			</section>
		</aside>
		<div class="span8">
			<h2> <%= current_user.name%>'s Microposts </h2>
			<%= render 'shared/feed'%>
		</div>
	</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>" >
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>" >
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.username %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>